baseurl: https://www.mcclimon.org
disablePathToLower: false
languageCode: en-us
title: "Michael McClimon"
MetaDataFormat: yaml
Paginate: 5
PluralizeListTitles: false
canonifyurls: false

taxonomies:
  tag: "tags"
