baseurl: https://www.mcclimon.org
disablePathToLower: false
languageCode: en-us
title: "Michael McClimon"
MetaDataFormat: yaml
Paginate: 5
PluralizeListTitles: false
canonifyurls: false
footnotereturnlinkcontents: "↩"
disablePathToLower: true

taxonomies:
  tag: "tags"

markup:
  highlight:
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 2
    wrapperClass: highlight
